version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
#    ports:
#        - "8080:80"
#    volumes:
#        - ./code:/code
#        - ./site.conf:/etc/nginx/conf.d/default.conf
#    links:
#        - php
  php:
    build: .
    volumes:
        - ./code:/var/www
    ports:
        - "8081:80"
    links:
        - mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      